### ISSUE TITLE
Transfer repo

### ISSUE THREAD

**Issue by ocramz** [ocramz/aeson-schema#27]
Hi @Fuuzetsu , perhaps it's faster if I take over this repo to cut a new release. Could you transfer it to me ? Thanks!

**Comment by Fuuzetsu** [comment]
I can only do it if you don't have a repo/fork with the same name already, which you do. Please delete your fork and I'll try to transfer it again. I think you have 1 day to accept it after that.

**Comment by ocramz** [comment]
Done, thanks for the heads up!

**Comment by Fuuzetsu** [comment]
sent request

**Comment by ocramz** [comment]
@Fuuzetsu thanks!

**Comment by Fuuzetsu** [comment]
I took the liberty of changing the various link repos in to `ocramz/aeson-schema`. I also re-checked that you're Hackage maintainer so we should be set there too.

You should probably add yourself to maintainers/copyright in cabal file.
